// import 'package:shoppinglist/utils/enums.dart';

// class Assets {
//   static String getAsset(EImageType type) {
//     switch (type) {
//       case EImageType.aceite:
//         return 'assets/alimentacion/aceite.png';
//       case EImageType.agua:
//         return 'assets/alimentacion/agua.png';
//       case EImageType.aguacate:
//         return 'assets/alimentacion/aguacate.png';
//       case EImageType.arroz:
//         return 'assets/alimentacion/arroz.png';
//       case EImageType.azucar:
//         return 'assets/alimentacion/azucar.png';
//       case EImageType.banana:
//         return 'assets/alimentacion/banana.png';
//       case EImageType.bebidaVegetal:
//         return 'assets/alimentacion/bebidaVegetal.png';
//       case EImageType.bio:
//         return 'assets/alimentacion/bio.png';
//       case EImageType.cafe:
//         return 'assets/alimentacion/cafe.png';
//       case EImageType.carne:
//         return 'assets/alimentacion/carne.png';
//       case EImageType.cereales:
//         return 'assets/alimentacion/cereales.png';
//       case EImageType.cerveza:
//         return 'assets/alimentacion/cerveza.png';
//       case EImageType.chocolate:
//         return 'assets/alimentacion/chocolate.png';
//       case EImageType.conserva:
//         return 'assets/alimentacion/conserva.png';
//       case EImageType.crema:
//         return 'assets/alimentacion/crema.png';
//       case EImageType.cremaCacao:
//         return 'assets/alimentacion/cremaCacao.png';
//       case EImageType.dulces:
//         return 'assets/alimentacion/dulces.png';
//       case EImageType.embutidos:
//         return 'assets/alimentacion/embutidos.png';
//       case EImageType.encurtidos:
//         return 'assets/alimentacion/encurtidos.png';
//       case EImageType.especias:
//         return 'assets/alimentacion/especias.png';
//       case EImageType.fresa:
//         return 'assets/alimentacion/fresa.png';
//       case EImageType.fruta:
//         return 'assets/alimentacion/frutas.png';
//       case EImageType.frutosSecos:
//         return 'assets/alimentacion/frutosSecos.png';
//       case EImageType.hamburguesa:
//         return 'assets/alimentacion/hamburguesa.png';
//       case EImageType.harina:
//         return 'assets/alimentacion/harina.png';
//       case EImageType.helado:
//         return 'assets/alimentacion/helado.png';
//       case EImageType.huevos:
//         return 'assets/alimentacion/huevos.png';
//       case EImageType.leche:
//         return 'assets/alimentacion/leche.png';
//       case EImageType.mantequilla:
//         return 'assets/alimentacion/mantequilla.png';
//       case EImageType.mermelada:
//         return 'assets/alimentacion/mermelada.png';
//       case EImageType.miel:
//         return 'assets/alimentacion/miel.png';
//       case EImageType.molde:
//         return 'assets/alimentacion/molde.png';
//       case EImageType.nachos:
//         return 'assets/alimentacion/nachos.png';
//       case EImageType.pan:
//         return 'assets/alimentacion/pan.png';
//       case EImageType.pasta:
//         return 'assets/alimentacion/pasta.png';
//       case EImageType.pescado:
//         return 'assets/alimentacion/pescado.png';
//       case EImageType.pizza:
//         return 'assets/alimentacion/pizza.png';
//       case EImageType.proteina:
//         return 'assets/alimentacion/proteina.png';
//       case EImageType.queso:
//         return 'assets/alimentacion/queso.png';
//       case EImageType.refresco:
//         return 'assets/alimentacion/refresco.png';
//       case EImageType.sal:
//         return 'assets/alimentacion/sal.png';
//       case EImageType.salsa:
//         return 'assets/alimentacion/salsa.png';
//       case EImageType.semillas:
//         return 'assets/alimentacion/semillas.png';
//       case EImageType.snack:
//         return 'assets/alimentacion/barrita.png';
//       case EImageType.te:
//         return 'assets/alimentacion/te.png';
//       case EImageType.verdura:
//         return 'assets/alimentacion/verdura.png';
//       case EImageType.vino:
//         return 'assets/alimentacion/vino.png';
//       case EImageType.vitaminas:
//         return 'assets/alimentacion/vitaminas.png';
//       case EImageType.yogur:
//         return 'assets/alimentacion/yogur.png';
//       case EImageType.zumo:
//         return 'assets/alimentacion/zumo.png';
//       case EImageType.legumbres:
//         return 'assets/alimentacion/legumbres.png';
//       case EImageType.watermelon:
//         return 'assets/alimentacion/watermelon.png';
//       case EImageType.gazpacho:
//         return 'assets/alimentacion/gazpacho.png';
//       case EImageType.precocinado:
//         return 'assets/alimentacion/precocinado.png';
//       case EImageType.croissant:
//         return 'assets/alimentacion/croissant.png';

//       case EImageType.bombilla:
//         return 'assets/otros/bombilla.png';
//       case EImageType.champu:
//         return 'assets/otros/champu.png';
//       case EImageType.cremaFacial:
//         return 'assets/otros/cremaFacial.png';
//       case EImageType.limpieza:
//         return 'assets/otros/limpieza.png';
//       case EImageType.maquillaje:
//         return 'assets/otros/maquillaje.png';
//       case EImageType.medicina:
//         return 'assets/otros/medicina.png';
//       case EImageType.papelHigienico:
//         return 'assets/otros/papelHigienico.png';
//       case EImageType.papeleria:
//         return 'assets/otros/papeleria.png';
//       case EImageType.pastaDientes:
//         return 'assets/otros/pastaDientes.png';
//       case EImageType.pila:
//         return 'assets/otros/pila.png';
//       case EImageType.piscina:
//         return 'assets/otros/piscina.png';
//       case EImageType.vela:
//         return 'assets/otros/vela.png';
//       case EImageType.spray:
//         return 'assets/otros/spray.png';
//       case EImageType.clothes:
//         return 'assets/otros/clothes.png';
//       case EImageType.shoes:
//         return 'assets/otros/shoes.png';
//       case EImageType.kettlebell:
//         return 'assets/otros/kettlebell.png';

//       case EImageType.genBanio:
//         return 'assets/genericos/genBanio.png';
//       case EImageType.genBebe:
//         return 'assets/genericos/genBebe.png';
//       case EImageType.genBicicleta:
//         return 'assets/genericos/genBicicleta.png';
//       case EImageType.genCoche:
//         return 'assets/genericos/genCoche.png';
//       case EImageType.genCocina:
//         return 'assets/genericos/genCocina.png';
//       case EImageType.genComedor:
//         return 'assets/genericos/genComedor.png';
//       case EImageType.genCongelados:
//         return 'assets/genericos/genCongelados.png';
//       case EImageType.genHabitacion:
//         return 'assets/genericos/genHabitacion.png';
//       case EImageType.genPlanta:
//         return 'assets/genericos/genPlanta.png';
//       case EImageType.genProducto:
//         return 'assets/genericos/genProducto.png';
//       case EImageType.genTaller:
//         return 'assets/genericos/genTaller.png';
//     }
//   }
// }
